# https://docs.docker.com/language/golang/build-images/

FROM golang:1.16-alpine



# Set the Current Working Directory inside the container
WORKDIR /app

# We want to populate the module cache based on the go.{mod,sum} files.
COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY *.go ./



EXPOSE 8080

# Run the binary program produced by `go install`
CMD ["/golog"]